export const CHANGE_VALUE_IN_CHECKUP = 'CHANGE_VALUE_IN_CHECKUP';
export const CHANGE_VALUE_IN_CHECKUP2 = 'CHANGE_VALUE_IN_CHECKUP2';

export const CHANGE_VALUE_LAB1 = 'CHANGE_VALUE_LAB1';
export const CHANGE_VALUE_LAB2 = 'CHANGE_VALUE_LAB2';
export const CHANGE_VALUE_LAB3 = 'CHANGE_VALUE_LAB3';
export const CHANGE_VALUE_LAB4 = 'CHANGE_VALUE_LAB4';


export const LOAD_DATA_For_CHECKUP = 'LOAD_DATA_FOR_CHECKUP';
export const LOAD_DATA_For_CHECKUP2 = 'LOAD_DATA_FOR_CHECKUP2';

export const LOAD_DATA_LAB1 = 'LOAD_DATA_LAB1';
export const LOAD_DATA_LAB2 = 'LOAD_DATA_LAB2';
export const LOAD_DATA_LAB3 = 'LOAD_DATA_LAB3';
export const LOAD_DATA_LAB4 = 'LOAD_DATA_LAB4';

