export const CHANGE_VALUE_IN_CHECKUP = 'CHANGE_VALUE_IN_CHECKUP';
export const CHANGE_VALUE_IN_CHECKUP2 = 'CHANGE_VALUE_IN_CHECKUP2';


export const LOAD_DATA_For_CHECKUP = 'LOAD_DATA_FOR_CHECKUP';
export const LOAD_DATA_For_CHECKUP2 = 'LOAD_DATA_FOR_CHECKUP2';
